# Generated by Django 4.0.4 on 2022-04-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='destination',
            new_name='trip',
        ),
    ]
